### ISSUE TITLE
Request Issues on Bomb Timer Page

### ISSUE THREAD

**Issue by itotallyrock** [farragar/bomb-timer#2]
When using the bomb timer, I visit the page and enter my name and submit.  But when I do this it says player not found.
![](http://i.imgur.com/OmrFi5v.png)

But if you goto the direct source http://www.farragar.com:3000/?username=R0CK it shows results and that I'm in a game.

![](http://i.imgur.com/kMmPgnE.png)

So I investigated through the network tab of Chrome DevTools and noticed a small error that could be simply fixed.

![](http://i.imgur.com/tCwhtUN.png)

The site is requesting http://www.farragar.com:3000/?username=R0CK but it is getting http://www.farragar.com/bomb_timer/www.farragar.com:3000?username=R0CK

**Comment by sicklydove** [comment]
Shiiit, my bad! Cheers buddy, should be fixed now.
